# syntax=docker/dockerfile:1@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# Build
FROM microservice-sdk-build AS build
ENV NODE_ENV=development
WORKDIR /workspace/app/backend-ts
COPY package.json .npmrc tsconfig.json ./
WORKDIR /workspace
RUN pnpm install

# Run
FROM microservice-sdk-build
WORKDIR /workspace/app/backend-ts
COPY --from=build --chown=node:node /workspace/app/backend-ts /workspace/app/backend-ts
COPY --from=build --chown=node:node /workspace/node_modules /workspace/node_modules
COPY --chown=node:node /src /workspace/app/backend-ts/src
USER node
EXPOSE 3001
WORKDIR /workspace
CMD [ "pnpm", "--filter", "backend-ts", "run", "dev" ]
