# syntax=docker/dockerfile:1@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# Build
FROM microservice-sdk-build AS build
ENV NODE_ENV=development
WORKDIR /workspace/app/backend-ts
COPY package.json .npmrc tsconfig.json ./
RUN npm install

# Run
FROM microservice-sdk-build
WORKDIR /workspace/app/backend-ts
COPY --from=build /workspace/app/backend-ts /workspace/app/backend-ts
COPY /src /workspace/app/backend-ts/src
EXPOSE 3001
WORKDIR /workspace
CMD [ "npm", "run", "dev", "-w", "app/backend-ts" ]
