# syntax=docker/dockerfile:1@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
FROM microservice-build
ENV NODE_ENV=development
WORKDIR /workspace
COPY /packages/@sos/sdk ./packages/@sos/sdk
COPY package.json package-lock.json tsconfig.json .npmrc ./
RUN npm install && npm run compile -w @sos/sdk

