name: demo-ts

# Add a new microservice docker-compose to the full stack
include:
  - shared/dapr/docker-compose.yaml
  - shared/db/docker-compose.yaml
  - shared/otel/docker-compose.yaml
  - app/backend-ts/docker-compose.yaml
  - app/web-nextjs/docker-compose.yaml

services:

  shell:
    profiles: [debug]
    image: alpine:3.21@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - dapr-net

networks:
  dapr-net: # here we set the network name
    driver: bridge
