# syntax=docker/dockerfile:1@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# Build
FROM microservice-build AS build
ENV NODE_ENV=development
WORKDIR /app
COPY package.json tsconfig.json tsconfig.app.json tsconfig.node.json eslint.config.js vite.config.ts index.html ./
RUN pnpm install
WORKDIR /app/public
COPY public .

# Run
FROM microservice-build
WORKDIR /app
COPY --from=build --chown=node:node /app /app
COPY --chown=node:node /src /app/src
USER node
EXPOSE 3001
CMD [ "pnpm", "run", "dev" ]
