# syntax=docker/dockerfile:1@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# Build
FROM microservice-build as build
ENV NODE_ENV=development
WORKDIR /app
COPY package.json tsconfig.json tsconfig.app.json tsconfig.node.json eslint.config.js vite.config.ts index.html ./
RUN npm install
WORKDIR /app/public
COPY public .

# Run
FROM microservice-build
WORKDIR /app
COPY --from=build /app /app
COPY /src /app/src
EXPOSE 3001
CMD [ "npm", "run", "dev" ]
