name: demo-ts

services:
  # Grafana OTEL collector, metrics, traces and logs. TODO: update dapr/config.yaml to wire this up
  grafana-otel:
    image: "docker.io/grafana/otel-lgtm@sha256:af7242c1a9608faf6d26e6f235392fd0c32b67258228f9a3cfc96e724974930c"
    ports:
      - "3200:3000"
      - "4318:4318"
    volumes:
      - "./config/prometheus.yaml:/otel-lgtm/prometheus.yaml"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health || exit 1"]
      interval: ${COMPOSE_HEALTHCHECK_INTERVAL:-10s}
      timeout: ${COMPOSE_HEALTHCHECK_TIMEOUT:-3s}
      retries: ${COMPOSE_HEALTHCHECK_RETRIES:-30}
      start_period: ${COMPOSE_HEALTHCHECK_START_PERIOD:-60s}
    networks:
      - dapr-net

networks:
  dapr-net: # here we set the network name
    driver: bridge
