# syntax=docker/dockerfile:1
# Build
FROM microservice-sdk-build as build
ENV NODE_ENV=development
WORKDIR /workspace/app/<%= name %>
COPY package.json tsconfig.json ./
RUN npm install

# Run
FROM microservice-sdk-build
WORKDIR /workspace/app/<%= name %>
# hadolint ignore=DL3021
COPY --from=build /workspace/app/<%= name %> /workspace/app/<%= name %>
# hadolint ignore=DL3021
COPY /src /workspace/app/<%= name %>/src
EXPOSE 3001
WORKDIR /workspace
CMD [ "npm", "run", "dev", "-w", "app/<%= name %>" ]
