# syntax=docker/dockerfile:1@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# Build
FROM microservice-sdk-build AS build
ENV NODE_ENV=development
WORKDIR /workspace/app/<%= name %>
COPY package.json tsconfig.json ./
WORKDIR /workspace
RUN pnpm install

# Run
FROM microservice-sdk-build
WORKDIR /workspace/app/<%= name %>
# hadolint ignore=DL3021
COPY --from=build /workspace/app/<%= name %> /workspace/app/<%= name %>
# hadolint ignore=DL3021
COPY --from=build /workspace/node_modules /workspace/node_modules
# hadolint ignore=DL3021
COPY /src /workspace/app/<%= name %>/src
EXPOSE 3001
WORKDIR /workspace
CMD [ "pnpm", "--filter", "<%= name %>", "run", "dev" ]
