# syntax=docker/dockerfile:1@sha256:4a43a54dd1fedceb30ba47e76cfcf2b47304f4161c0caeac2db1c61804ea3c91
# Build
FROM microservice-sdk-build as build
ENV NODE_ENV=development
WORKDIR /workspace/app/<%= name %>
COPY package.json tsconfig.json ./
RUN npm install

# Run
FROM microservice-sdk-build
WORKDIR /workspace/app/<%= name %>
# hadolint ignore=DL3021
COPY --from=build /workspace/app/<%= name %> /workspace/app/<%= name %>
# hadolint ignore=DL3021
COPY /src /workspace/app/<%= name %>/src
EXPOSE 3001
WORKDIR /workspace
CMD [ "npm", "run", "dev", "-w", "app/<%= name %>" ]
