# Build
FROM docker.io/node:24-alpine AS build
ENV NODE_ENV=development
WORKDIR /app
COPY package.json tsconfig.json tsconfig.app.json tsconfig.node.json eslint.config.js vite.config.ts index.html ./
RUN npm install
WORKDIR /app/public
COPY public .

# Run
FROM docker.io/node:24-alpine AS runtime
WORKDIR /app
COPY --from=build /app /app
COPY /src /app/src
EXPOSE 3001
CMD [ "npm", "run", "dev" ]
