# syntax=docker/dockerfile:1@sha256:87999aa3d42bdc6bea60565083ee17e86d1f3339802f543c0d03998580f9cb89
# Build
FROM microservice-build AS build
ENV NODE_ENV=development
WORKDIR /app
COPY package.json next.config.ts postcss.config.mjs tsconfig.json eslint.config.mjs ./
RUN pnpm install
WORKDIR /app/public
COPY public ./

# Run
FROM microservice-build
WORKDIR /app
COPY --from=build /app /app
COPY /src /app/src
EXPOSE 3001
CMD [ "pnpm", "run", "dev" ]
