# syntax=docker/dockerfile:1@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# Build
FROM microservice-build AS build
ENV NODE_ENV=development
WORKDIR /app
COPY package.json next.config.ts postcss.config.mjs tsconfig.json eslint.config.mjs ./
RUN pnpm install
WORKDIR /app/public
COPY public ./

# Run
FROM microservice-build
WORKDIR /app
COPY --from=build /app /app
COPY /src /app/src
EXPOSE 3001
CMD [ "pnpm", "run", "dev" ]
