# syntax=docker/dockerfile:1@sha256:4a43a54dd1fedceb30ba47e76cfcf2b47304f4161c0caeac2db1c61804ea3c91
# Build
FROM microservice-build as build
ENV NODE_ENV=development
WORKDIR /app
COPY package.json next.config.ts postcss.config.mjs tsconfig.json eslint.config.mjs ./
RUN npm install
WORKDIR /app/public
COPY public ./

# Run
FROM microservice-build
WORKDIR /app
COPY --from=build /app /app
COPY /src /app/src
EXPOSE 3001
CMD [ "npm", "run", "dev" ]
